-- WW's Map+ 1.5.1

NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_RESISTANCE = 100.0
NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_DIPLOMACY = 100.0
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_STATE = 0.0
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_SUPPLY_AREA = 0.0
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_STRATEGIC_REGIONS = 0.0
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_RESISTANCE = 0.0
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_FACTIONS = 0.0
NDefines.NGraphics.GRADIENT_BORDERS_OPTIMIZATION_RANGE = 20.0
NDefines.NGraphics.STRATEGIC_AIR_COLOR_NEUTRAL = {0.3, 0.4, 0.8, 1}
NDefines.NGraphics.STRATEGIC_NAVY_COLOR_MISSION = {0.5, 0.25, 0.0, 1}
NDefines.NGraphics.STRATEGIC_NAVY_COLOR_NEUTRAL = {0.15, 0.20, 0.3, 1}
NDefines.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {300, 500, 1000}
NDefines.NGraphics.MAP_ICONS_GROUP_CAM_DISTANCE = 230
NDefines.NGraphics.CAPITAL_ICON_CUTOFF = 1500
NDefines.NGraphics.MAP_ICONS_STATE_GROUP_CAM_DISTANCE = 480
NDefines.NGraphics.MAP_ICONS_STRATEGIC_GROUP_CAM_DISTANCE = 800
NDefines.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE = 220
NDefines.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE_STRATEGIC = 220
NDefines.NGraphics.FRIEND_COLOR  = {1.0, 1.0, 1.0}
NDefines.NGraphics.NEUTRAL_COLOR = {0.7, 0.7, 0.7}